name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

env:
  IMAGE_NAME: "homecentr/haraka-relay"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@master
      
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@master      

      - name: Install dependencies
        run: yarn

      - name: Build Docker image
        run: yarn build

      - name: Test Docker image
        run: yarn test
        env: # To allow downloading packages
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}